# Generated by Django 5.1.2 on 2024-12-30 20:02

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('ART', 'Artist'), ('ORG', 'Organiser'), ('PUB', 'Public')], null=True, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.user_directory_path),
        ),
    ]
