# Generated by Django 5.1.2 on 2025-01-13 20:22

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profileimages_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profileimages',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.user_directory_path_image),
        ),
    ]
