# Generated by Django 5.1.2 on 2025-01-13 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_slug_alter_profileimages_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='slug',
            new_name='stage_slug',
        ),
    ]
