version: "3"
services:
  web:
    build: .
    command: [  "uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini"]
    restart: always
    volumes:
      - .:/code
    environment:
     - DJANGO_SETTINGS_MODULE=gigma.settings
  nginx:
    image: nginx:1.23.1
    depends_on:
      - web
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code
      - /etc/letsencrypt/live/gigma.co.uk/fullchain.pem:/etc/letsencrypt/live/gigma.co.uk/fullchain.pem
      - /etc/letsencrypt/live/gigma.co.uk/privkey.pem:/etc/letsencrypt/live/gigma.co.uk/privkey.pem
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
    ports:
      - "80:80"
      - "443:443"