version: "3"
services:
  web:
    build: .
    command: [  "uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini"]
    restart: always
    volumes:
      - .:/code
    environment:
     - DJANGO_SETTINGS_MODULE=gigma.settings
  nginx:
    image: nginx:1.23.1
    depends_on:
      - web
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code
      # - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
    ports:
      - "80:80"
      - "443:443"